"""add vehicle_type to diagnostic sessions

Revision ID: 8539d59fc1ac
Revises: a1b2c3d4e5f6
Create Date: 2026-08-21 02:21:18.168547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8539d59fc1ac'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnostic_sessions', sa.Column('vehicle_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnostic_sessions', 'vehicle_type')
    # ### end Alembic commands ###
