"""add_unique_index_to_confirmed_cases_source_result_id

Revision ID: 88dd5f292f91
Revises: f265ee8eb558
Create Date: 2026-08-25 20:05:00.898785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88dd5f292f91'
down_revision: Union[str, Sequence[str], None] = 'f265ee8eb558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_confirmed_diagnostic_cases_source_result_id'), 'confirmed_diagnostic_cases', ['source_result_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmed_diagnostic_cases_source_result_id'), table_name='confirmed_diagnostic_cases')
    # ### end Alembic commands ###
