"""add_confirmed_diagnostic_cases

Revision ID: f265ee8eb558
Revises: 7686324753fa
Create Date: 2026-08-24 14:33:52.330215

"""
from typing import Sequence, Union
import pgvector.sqlalchemy

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f265ee8eb558'
down_revision: Union[str, Sequence[str], None] = '7686324753fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmed_diagnostic_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('symptom_text', sa.Text(), nullable=False),
    sa.Column('dtc_codes', sa.Text(), nullable=True),
    sa.Column('confirmed_fault', sa.Text(), nullable=False),
    sa.Column('confirmed_fault_description', sa.Text(), nullable=True),
    sa.Column('repair_suggestion', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('case_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('source_result_id', sa.UUID(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmed_diagnostic_cases_make'), 'confirmed_diagnostic_cases', ['make'], unique=False)
    op.create_index(op.f('ix_confirmed_diagnostic_cases_model'), 'confirmed_diagnostic_cases', ['model'], unique=False)
    op.create_index(op.f('ix_confirmed_diagnostic_cases_year'), 'confirmed_diagnostic_cases', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmed_diagnostic_cases_year'), table_name='confirmed_diagnostic_cases')
    op.drop_index(op.f('ix_confirmed_diagnostic_cases_model'), table_name='confirmed_diagnostic_cases')
    op.drop_index(op.f('ix_confirmed_diagnostic_cases_make'), table_name='confirmed_diagnostic_cases')
    op.drop_table('confirmed_diagnostic_cases')
    # ### end Alembic commands ###
